[package]
name = "seedwing-send-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.64"
seedwing-policy-engine = { git = "https://github.com/seedwing-io/seedwing-policy" }
tokio = { version = "1", features = ["full"] }
